import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/storage/repositories.dart';
import '../../../core/models/relationship.dart';
import '../../../core/models/generated_output.dart';
import '../../../core/models/constellation.dart';
import '../../../core/utils/constants.dart';
import '../../../core/widgets/examples_sheet.dart';
import '../../../app/theme/app_theme.dart';
import '../../shared/tone_selector.dart';
import '../../shared/constellation_card.dart';
import '../constellation/constellation_tab.dart';

/// Helper to convert RelationshipExampleRef to ExampleItem for the examples sheet
ExampleItem _convertToExampleItem(RelationshipExampleRef ref) {
  return ExampleItem(
    characterName: ref.characterName ?? 'Character',
    reference: ExampleReference(
      title: ref.reference?.title ?? 'Unknown',
      year: ref.reference?.year ?? '',
      medium: ref.reference?.medium ?? 'film',
    ),
    situation: ref.situation ?? '',
    actions: ref.actions,
    outcomeAndCost: ref.outcomeAndCost,
    tier: ref.tier,
    autoGenerated: ref.tier == 'B',
  );
}

class RelationshipTab extends ConsumerStatefulWidget {
  const RelationshipTab({super.key});

  @override
  ConsumerState<RelationshipTab> createState() => _RelationshipTabState();
}

class _RelationshipTabState extends ConsumerState<RelationshipTab>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  String _selectedType = AppConstants.relationshipTypePlatonic;

  // Updated tab structure per spec - relationship-centered with What-If scenarios
  final List<_TabItem> _tabItems = const [
    _TabItem(title: 'Myth', icon: Icons.auto_stories),
    _TabItem(title: 'Archetypes', icon: Icons.auto_awesome), // NEW: Constellation
    _TabItem(title: 'Field', icon: Icons.blur_on),
    _TabItem(title: 'Ease', icon: Icons.favorite_border), // NEW: Where it works
    _TabItem(title: 'Rupture', icon: Icons.warning_amber), // NEW: Where it breaks
    _TabItem(title: 'Shadow', icon: Icons.contrast),
    _TabItem(title: 'Conflict', icon: Icons.forum),
    _TabItem(title: 'Growth', icon: Icons.trending_up),
    _TabItem(title: 'What-If', icon: Icons.psychology), // NEW: Scenarios
    _TabItem(title: 'Next', icon: Icons.directions),
  ];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: _tabItems.length, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  void _changeRelationshipType(String type) {
    if (type != _selectedType) {
      setState(() => _selectedType = type);
      ref.read(relationshipRepositoryProvider.notifier).updateRelationshipType(type);
    }
  }

  Color get _accentColor => _selectedType == AppConstants.relationshipTypeRomantic
      ? const Color(0xFFE91E63)
      : const Color(0xFF2196F3);

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;
    final relationshipAsync = ref.watch(relationshipRepositoryProvider);
    final outputAsync = ref.watch(relationshipOutputRepositoryProvider);
    // Use effective output which includes tone-rendered content when available
    final effectiveOutput = ref.watch(effectiveRelationshipOutputProvider);
    // Watch tone state for loading state
    final toneState = ref.watch(toneRepositoryProvider);

    return Stack(
      children: [
        relationshipAsync.when(
          loading: () => _buildScaffold(context, isDark, null, true),
          error: (e, _) => _buildErrorState(context, e.toString()),
          data: (relationship) {
            if (relationship == null || !relationship.enabled) {
              return _buildNotEnabledState(context);
            }

            _selectedType = relationship.relationshipType;

            return outputAsync.when(
              loading: () => _buildScaffold(context, isDark, null, true),
              error: (e, _) => _buildScaffold(context, isDark, null, false, error: e.toString()),
              data: (_) => _buildScaffold(context, isDark, effectiveOutput, false),
            );
          },
        ),
        // Tone loading overlay
        if (toneState.isLoading)
          Positioned.fill(
            child: Container(
              color: theme.scaffoldBackgroundColor.withOpacity(0.85),
              child: const Center(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    CircularProgressIndicator(),
                    SizedBox(height: 16),
                    Text('Adjusting narrative tone...'),
                  ],
                ),
              ),
            ),
          ),
      ],
    );
  }

  Widget _buildScaffold(BuildContext context, bool isDark, RelationshipOutput? output, bool isLoading, {String? error}) {
    final theme = Theme.of(context);
    
    return Scaffold(
      appBar: AppBar(
        title: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [_accentColor, _accentColor.withOpacity(0.7)],
                ),
                borderRadius: BorderRadius.circular(10),
              ),
              child: Icon(
                _selectedType == AppConstants.relationshipTypeRomantic
                    ? Icons.favorite
                    : Icons.people,
                color: Colors.white,
                size: 20,
              ),
            ),
            const SizedBox(width: 12),
            Text(_selectedType == AppConstants.relationshipTypeRomantic
                ? 'Romantic Bond'
                : 'Friendship Bond'),
          ],
        ),
        actions: [
          // Tone selector
          ToneSelector(compact: true, accentColor: _accentColor),
          // Type switcher popup
          PopupMenuButton<String>(
            icon: const Icon(Icons.swap_horiz),
            tooltip: 'Change Type',
            onSelected: _changeRelationshipType,
            itemBuilder: (context) => [
              PopupMenuItem(
                value: AppConstants.relationshipTypeRomantic,
                child: Row(
                  children: [
                    Icon(Icons.favorite, 
                      color: _selectedType == AppConstants.relationshipTypeRomantic 
                          ? const Color(0xFFE91E63) : null,
                      size: 20,
                    ),
                    const SizedBox(width: 8),
                    const Text('Romantic'),
                  ],
                ),
              ),
              PopupMenuItem(
                value: AppConstants.relationshipTypePlatonic,
                child: Row(
                  children: [
                    Icon(Icons.people,
                      color: _selectedType == AppConstants.relationshipTypePlatonic
                          ? const Color(0xFF2196F3) : null,
                      size: 20,
                    ),
                    const SizedBox(width: 8),
                    const Text('Platonic'),
                  ],
                ),
              ),
            ],
          ),
          IconButton(
            icon: const Icon(Icons.edit_outlined),
            tooltip: 'Edit Characters',
            onPressed: () {
              context.push('/characters');
            },
          ),
          IconButton(
            icon: const Icon(Icons.refresh),
            tooltip: 'Regenerate',
            onPressed: () {
              ref.read(relationshipOutputRepositoryProvider.notifier).regenerate();
            },
          ),
        ],
        bottom: TabBar(
          controller: _tabController,
          isScrollable: true,
          tabAlignment: TabAlignment.start,
          indicatorSize: TabBarIndicatorSize.label,
          dividerColor: Colors.transparent,
          labelColor: _accentColor,
          unselectedLabelColor: isDark ? Colors.grey.shade400 : Colors.grey.shade600,
          indicatorColor: _accentColor,
          tabs: _tabItems.map((item) => Tab(
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(item.icon, size: 18),
                const SizedBox(width: 6),
                Text(item.title),
              ],
            ),
          )).toList(),
        ),
      ),
      body: Column(
        children: [
          // Disclaimer banner
          _buildDisclaimer(context),
          // Content
          Expanded(
            child: error != null
                ? _buildErrorContent(context, error)
                : isLoading
                    ? _buildLoadingContent(context)
                    : output == null
                        ? _buildLoadingContent(context)
                        : TabBarView(
                            controller: _tabController,
                            children: [
                              _RelationshipMythTab(output: output, accentColor: _accentColor),
                              const ConstellationTab(embedded: true, isRelationship: true), // NEW: Archetypes
                              _RelationshipModuleTab(output: output, moduleKey: 'relationalField', title: 'Relational Field', accentColor: _accentColor),
                              _EaseZonesTab(output: output, accentColor: _accentColor), // NEW
                              _RuptureLoopsTab(output: output, accentColor: _accentColor), // NEW
                              _RelationshipModuleTab(output: output, moduleKey: 'projectionShadow', title: 'Projection & Shadow', accentColor: _accentColor),
                              _RelationshipModuleTab(output: output, moduleKey: 'communicationConflict', title: 'Communication', accentColor: _accentColor),
                              _RelationshipModuleTab(output: output, moduleKey: 'growthPath', title: 'Growth Path', accentColor: _accentColor),
                              _WhatIfScenariosTab(output: output, accentColor: _accentColor), // NEW
                              _RelationshipNextStepsTab(output: output, accentColor: _accentColor),
                            ],
                          ),
          ),
        ],
      ),
    );
  }

  Widget _buildDisclaimer(BuildContext context) {
    final theme = Theme.of(context);
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: Colors.amber.withOpacity(0.1),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: Colors.amber.withOpacity(0.3)),
      ),
      child: Row(
        children: [
          Icon(Icons.info_outline, color: Colors.amber.shade700, size: 18),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              'Based on your perception. Accuracy improves if they make their own profile.',
              style: theme.textTheme.bodySmall?.copyWith(
                color: Colors.amber.shade800,
                fontSize: 11,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildLoadingContent(BuildContext context) {
    final theme = Theme.of(context);
    
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          SizedBox(
            width: 50,
            height: 50,
            child: CircularProgressIndicator(
              strokeWidth: 3,
              color: _accentColor,
            ),
          ),
          const SizedBox(height: 20),
          Text(
            'Analyzing relationship dynamics...',
            style: theme.textTheme.titleMedium,
          ),
          const SizedBox(height: 8),
          Text(
            'This may take a moment',
            style: theme.textTheme.bodySmall?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildErrorContent(BuildContext context, String error) {
    final theme = Theme.of(context);
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.error_outline, size: 48, color: theme.colorScheme.error),
            const SizedBox(height: 16),
            Text('Error', style: theme.textTheme.titleLarge),
            const SizedBox(height: 8),
            Text(error, textAlign: TextAlign.center, style: TextStyle(color: theme.colorScheme.error)),
            const SizedBox(height: 24),
            ElevatedButton.icon(
              onPressed: () => ref.read(relationshipOutputRepositoryProvider.notifier).regenerate(),
              icon: const Icon(Icons.refresh),
              label: const Text('Retry'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildNotEnabledState(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(title: const Text('Relationship')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.people_outline, size: 80, color: theme.colorScheme.outline),
              const SizedBox(height: 24),
              Text(
                'Relationship Not Enabled',
                style: theme.textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w600),
              ),
              const SizedBox(height: 12),
              Text(
                'Add partner or friend characters on the character entry screen to explore relationship dynamics.',
                textAlign: TextAlign.center,
                style: theme.textTheme.bodyMedium?.copyWith(color: theme.colorScheme.onSurfaceVariant),
              ),
              const SizedBox(height: 24),
              ElevatedButton.icon(
                onPressed: () => context.push('/characters'),
                icon: const Icon(Icons.add),
                label: const Text('Add Characters'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildErrorState(BuildContext context, String error) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(title: const Text('Relationship')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.error_outline, size: 64, color: theme.colorScheme.error),
              const SizedBox(height: 16),
              Text('Error loading relationship', style: theme.textTheme.titleLarge),
              const SizedBox(height: 8),
              Text(error, textAlign: TextAlign.center, style: TextStyle(color: theme.colorScheme.error)),
              const SizedBox(height: 24),
              ElevatedButton.icon(
                onPressed: () => ref.read(relationshipOutputRepositoryProvider.notifier).regenerate(),
                icon: const Icon(Icons.refresh),
                label: const Text('Retry'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _TabItem {
  final String title;
  final IconData icon;
  const _TabItem({required this.title, required this.icon});
}

// ============================================================================
// MYTH TAB
// ============================================================================

class _RelationshipMythTab extends ConsumerStatefulWidget {
  final RelationshipOutput output;
  final Color accentColor;

  const _RelationshipMythTab({required this.output, required this.accentColor});

  @override
  ConsumerState<_RelationshipMythTab> createState() => _RelationshipMythTabState();
}

class _RelationshipMythTabState extends ConsumerState<_RelationshipMythTab> {
  final Set<int> _revealedSections = {};

  @override
  void initState() {
    super.initState();
    _startProgressiveReveal();
  }

  void _startProgressiveReveal() {
    for (int i = 0; i < 4; i++) {
      Future.delayed(Duration(milliseconds: 150 * i), () {
        if (mounted) setState(() => _revealedSections.add(i));
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final myth = widget.output.myth;

    if (myth == null) {
      return const Center(child: Text('No myth data available'));
    }

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        // Relationship Constellation Card (NEW)
        _buildConstellationSection(),
        const SizedBox(height: 12),
        
        // Title card
        _buildAnimatedCard(
          0,
          _buildSectionCard(
            context,
            title: myth.title ?? 'Your Relationship Myth',
            content: myth.summary ?? '',
            icon: Icons.auto_stories,
            accentColor: widget.accentColor,
            isHighlighted: true,
          ),
        ),
        const SizedBox(height: 12),
        // Story card
        _buildAnimatedCard(
          1,
          _buildSectionCard(
            context,
            title: 'The Story',
            content: myth.story ?? '',
            icon: Icons.menu_book,
            accentColor: const Color(0xFF8B5CF6),
          ),
        ),
        const SizedBox(height: 12),
        // Themes card
        if (myth.themes.isNotEmpty)
          _buildAnimatedCard(
            2,
            _buildThemesCard(context, myth.themes),
          ),
      ],
    );
  }

  Widget _buildAnimatedCard(int index, Widget child) {
    final isRevealed = _revealedSections.contains(index);
    return AnimatedOpacity(
      duration: const Duration(milliseconds: 400),
      opacity: isRevealed ? 1.0 : 0.3,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 400),
        transform: Matrix4.translationValues(isRevealed ? 0 : 20, 0, 0),
        child: child,
      ),
    );
  }

  Widget _buildConstellationSection() {
    final constellationAsync = ref.watch(relationshipConstellationProvider);

    return constellationAsync.when(
      data: (response) {
        if (response == null || response.relationshipConstellation == null) {
          return const SizedBox.shrink();
        }
        return RelationshipConstellationCard(
          constellation: response.relationshipConstellation!,
        );
      },
      loading: () => Container(
        margin: const EdgeInsets.symmetric(vertical: 8),
        padding: const EdgeInsets.all(24),
        decoration: BoxDecoration(
          color: Theme.of(context).colorScheme.surfaceContainerHighest.withOpacity(0.5),
          borderRadius: BorderRadius.circular(16),
        ),
        child: const Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              CircularProgressIndicator(strokeWidth: 2),
              SizedBox(height: 12),
              Text('Loading shared archetypes...'),
            ],
          ),
        ),
      ),
      error: (_, __) => const SizedBox.shrink(),
    );
  }

  Widget _buildSectionCard(
    BuildContext context, {
    required String title,
    required String content,
    required IconData icon,
    required Color accentColor,
    bool isHighlighted = false,
  }) {
    final theme = Theme.of(context);
    
    return Card(
      elevation: isHighlighted ? 4 : 1,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: isHighlighted
            ? BorderSide(color: accentColor.withOpacity(0.3), width: 1.5)
            : BorderSide.none,
      ),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: accentColor.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Icon(icon, color: accentColor, size: 20),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    title,
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Text(
              content,
              style: theme.textTheme.bodyMedium?.copyWith(
                height: 1.6,
                fontStyle: isHighlighted ? FontStyle.italic : FontStyle.normal,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildThemesCard(BuildContext context, List<String> themes) {
    final theme = Theme.of(context);
    
    return Card(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: const Color(0xFF14B8A6).withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Icon(Icons.tag, color: Color(0xFF14B8A6), size: 20),
                ),
                const SizedBox(width: 12),
                Text(
                  'Themes',
                  style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: themes.map((t) => Chip(
                label: Text(t),
                backgroundColor: theme.colorScheme.surfaceContainerHighest,
              )).toList(),
            ),
          ],
        ),
      ),
    );
  }
}

// ============================================================================
// MODULE TAB (Generic for most modules)
// ============================================================================

class _RelationshipModuleTab extends StatefulWidget {
  final RelationshipOutput output;
  final String moduleKey;
  final String title;
  final Color accentColor;

  const _RelationshipModuleTab({
    required this.output,
    required this.moduleKey,
    required this.title,
    required this.accentColor,
  });

  @override
  State<_RelationshipModuleTab> createState() => _RelationshipModuleTabState();
}

class _RelationshipModuleTabState extends State<_RelationshipModuleTab> {
  final Set<int> _revealedSections = {};

  @override
  void initState() {
    super.initState();
    _startProgressiveReveal();
  }

  void _startProgressiveReveal() {
    for (int i = 0; i < 5; i++) {
      Future.delayed(Duration(milliseconds: 150 * i), () {
        if (mounted) setState(() => _revealedSections.add(i));
      });
    }
  }

  ModuleNarrative? _getNarrative() {
    final narrative = widget.output.narrative;
    if (narrative == null) return null;
    
    switch (widget.moduleKey) {
      case 'relationalField': return narrative.relationalField;
      case 'attractionBonding': return narrative.attractionBonding;
      case 'projectionShadow': return narrative.projectionShadow;
      case 'egoPersonaMismatch': return narrative.egoPersonaMismatch;
      case 'communicationConflict': return narrative.communicationConflict;
      case 'needsBoundaries': return narrative.needsBoundaries;
      case 'growthPath': return narrative.growthPath;
      case 'redFlagsRepair': return narrative.redFlagsRepair;
      default: return null;
    }
  }

  List<RelationshipExampleRef>? _getExamples() {
    final examples = widget.output.examples;
    if (examples == null) return null;
    
    switch (widget.moduleKey) {
      case 'relationalField': return examples.relationalField;
      case 'attractionBonding': return examples.attractionBonding;
      case 'projectionShadow': return examples.projectionShadow;
      case 'egoPersonaMismatch': return examples.egoPersonaMismatch;
      case 'communicationConflict': return examples.communicationConflict;
      case 'needsBoundaries': return examples.needsBoundaries;
      case 'growthPath': return examples.growthPath;
      case 'redFlagsRepair': return examples.redFlagsRepair;
      default: return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final narrative = _getNarrative();
    final examples = _getExamples();

    if (narrative == null) {
      return Center(child: Text('No ${widget.title} data available'));
    }

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        // Summary card
        if (narrative.summary != null)
          _buildAnimatedCard(0, _buildSummaryCard(context, narrative.summary!)),
        
        const SizedBox(height: 12),
        
        // Story card
        if (narrative.story != null)
          _buildAnimatedCard(1, _buildStoryCard(context, narrative.story!)),
        
        const SizedBox(height: 12),
        
        // Analysis bullets
        if (narrative.analysisBullets.isNotEmpty)
          _buildAnimatedCard(2, _buildBulletsCard(context, narrative.analysisBullets)),
        
        // Examples button (popup like Me tab)
        if (examples != null && examples.isNotEmpty) ...[
          const SizedBox(height: 16),
          _buildAnimatedCard(3, _buildExamplesButton(context, examples)),
        ],
      ],
    );
  }

  Widget _buildAnimatedCard(int index, Widget child) {
    final isRevealed = _revealedSections.contains(index);
    return AnimatedOpacity(
      duration: const Duration(milliseconds: 400),
      opacity: isRevealed ? 1.0 : 0.3,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 400),
        transform: Matrix4.translationValues(isRevealed ? 0 : 20, 0, 0),
        child: child,
      ),
    );
  }

  Widget _buildSummaryCard(BuildContext context, String summary) {
    final theme = Theme.of(context);
    
    return Card(
      elevation: 2,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
        side: BorderSide(color: widget.accentColor.withOpacity(0.3), width: 1.5),
      ),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: widget.accentColor.withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Icon(Icons.summarize, color: widget.accentColor, size: 20),
                ),
                const SizedBox(width: 12),
                Text(
                  'Summary',
                  style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Text(
              summary,
              style: theme.textTheme.bodyLarge?.copyWith(
                fontStyle: FontStyle.italic,
                height: 1.5,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStoryCard(BuildContext context, String story) {
    final theme = Theme.of(context);
    
    return Card(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: const Color(0xFF8B5CF6).withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Icon(Icons.menu_book, color: Color(0xFF8B5CF6), size: 20),
                ),
                const SizedBox(width: 12),
                Text(
                  'The Narrative',
                  style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Text(story, style: theme.textTheme.bodyMedium?.copyWith(height: 1.7)),
          ],
        ),
      ),
    );
  }

  Widget _buildBulletsCard(BuildContext context, List<String> bullets) {
    final theme = Theme.of(context);
    
    return Card(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: const Color(0xFF14B8A6).withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Icon(Icons.checklist, color: Color(0xFF14B8A6), size: 20),
                ),
                const SizedBox(width: 12),
                Text(
                  'Key Points',
                  style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600),
                ),
              ],
            ),
            const SizedBox(height: 16),
            ...bullets.map((bullet) => Padding(
              padding: const EdgeInsets.only(bottom: 8),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(Icons.arrow_right, size: 20, color: widget.accentColor),
                  const SizedBox(width: 8),
                  Expanded(child: Text(bullet, style: theme.textTheme.bodyMedium)),
                ],
              ),
            )),
          ],
        ),
      ),
    );
  }

  Widget _buildExamplesButton(BuildContext context, List<RelationshipExampleRef> examples) {
    final theme = Theme.of(context);
    
    return Card(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: InkWell(
        onTap: () {
          final converted = examples.map(_convertToExampleItem).toList();
          showExamplesSheet(
            context: context,
            examples: converted,
            sectionTitle: widget.title,
          );
        },
        borderRadius: BorderRadius.circular(12),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Row(
            children: [
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: widget.accentColor.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Icon(
                  Icons.movie_outlined,
                  color: widget.accentColor,
                  size: 24,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'View Examples',
                      style: theme.textTheme.titleMedium?.copyWith(
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      '${examples.length} example${examples.length > 1 ? 's' : ''} from their stories',
                      style: theme.textTheme.bodySmall?.copyWith(
                        color: theme.colorScheme.onSurfaceVariant,
                      ),
                    ),
                  ],
                ),
              ),
              Icon(
                Icons.chevron_right,
                color: theme.colorScheme.onSurfaceVariant,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ============================================================================
// NEXT STEPS TAB
// ============================================================================

class _RelationshipNextStepsTab extends StatefulWidget {
  final RelationshipOutput output;
  final Color accentColor;

  const _RelationshipNextStepsTab({required this.output, required this.accentColor});

  @override
  State<_RelationshipNextStepsTab> createState() => _RelationshipNextStepsTabState();
}

class _RelationshipNextStepsTabState extends State<_RelationshipNextStepsTab> {
  final Set<int> _revealedSections = {};

  @override
  void initState() {
    super.initState();
    _startProgressiveReveal();
  }

  void _startProgressiveReveal() {
    final count = (widget.output.narrative?.nextSteps?.length ?? 0) + 1;
    for (int i = 0; i < count; i++) {
      Future.delayed(Duration(milliseconds: 150 * i), () {
        if (mounted) setState(() => _revealedSections.add(i));
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final nextSteps = widget.output.narrative?.nextSteps;
    final examples = widget.output.examples?.nextSteps;

    if (nextSteps == null || nextSteps.isEmpty) {
      return const Center(child: Text('No next steps available'));
    }

    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: nextSteps.length + (examples != null && examples.isNotEmpty ? 1 : 0),
      itemBuilder: (context, index) {
        if (index < nextSteps.length) {
          final step = nextSteps[index];
          final isRevealed = _revealedSections.contains(index);
          
          return AnimatedOpacity(
            duration: const Duration(milliseconds: 400),
            opacity: isRevealed ? 1.0 : 0.3,
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 400),
              transform: Matrix4.translationValues(isRevealed ? 0 : 20, 0, 0),
              child: Card(
                margin: const EdgeInsets.only(bottom: 12),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                child: Padding(
                  padding: const EdgeInsets.all(20),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Container(
                            width: 36,
                            height: 36,
                            decoration: BoxDecoration(
                              gradient: LinearGradient(
                                colors: [widget.accentColor, widget.accentColor.withOpacity(0.7)],
                              ),
                              shape: BoxShape.circle,
                            ),
                            child: Center(
                              child: Text(
                                '${index + 1}',
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontWeight: FontWeight.bold,
                                  fontSize: 16,
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Text(
                              step.situation ?? 'Situation ${index + 1}',
                              style: theme.textTheme.titleMedium?.copyWith(
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ),
                        ],
                      ),
                      if (step.guidance != null && step.guidance!.isNotEmpty) ...[
                        const SizedBox(height: 16),
                        Text(
                          step.guidance!,
                          style: theme.textTheme.bodyMedium?.copyWith(height: 1.6),
                        ),
                      ],
                    ],
                  ),
                ),
              ),
            ),
          );
        }
        
        // Examples button - only show if examples exist
        if (examples == null || examples.isEmpty) {
          return const SizedBox.shrink();
        }
        
        return Card(
          margin: const EdgeInsets.only(top: 8),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
          child: InkWell(
            onTap: () {
              final converted = examples.map(_convertToExampleItem).toList();
              showExamplesSheet(
                context: context,
                examples: converted,
                sectionTitle: 'Next Steps',
              );
            },
            borderRadius: BorderRadius.circular(12),
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(10),
                    decoration: BoxDecoration(
                      color: widget.accentColor.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(10),
                    ),
                    child: Icon(
                      Icons.movie_outlined,
                      color: widget.accentColor,
                      size: 24,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'View Examples',
                          style: theme.textTheme.titleMedium?.copyWith(
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          '${examples.length} example${examples.length > 1 ? 's' : ''} from their stories',
                          style: theme.textTheme.bodySmall?.copyWith(
                            color: theme.colorScheme.onSurfaceVariant,
                          ),
                        ),
                      ],
                    ),
                  ),
                  Icon(
                    Icons.chevron_right,
                    color: theme.colorScheme.onSurfaceVariant,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}

// ============================================================================
// NEW: Ease Zones Tab - Where the relationship works naturally
// ============================================================================
class _EaseZonesTab extends StatefulWidget {
  final RelationshipOutput output;
  final Color accentColor;

  const _EaseZonesTab({required this.output, required this.accentColor});

  @override
  State<_EaseZonesTab> createState() => _EaseZonesTabState();
}

class _EaseZonesTabState extends State<_EaseZonesTab> {
  final Set<int> _revealedSections = {};

  @override
  void initState() {
    super.initState();
    _startProgressiveReveal();
  }

  void _startProgressiveReveal() {
    final zones = widget.output.easeZones?.zones ?? [];
    for (int i = 0; i <= zones.length; i++) {
      Future.delayed(Duration(milliseconds: 150 * i), () {
        if (mounted) setState(() => _revealedSections.add(i));
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final easeZones = widget.output.easeZones;

    if (easeZones == null) {
      return Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.favorite_border, size: 48, color: widget.accentColor.withOpacity(0.5)),
            const SizedBox(height: 16),
            Text('Ease zones data not available', style: theme.textTheme.bodyLarge),
            const SizedBox(height: 8),
            Text(
              'Try regenerating the relationship analysis',
              style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant),
            ),
          ],
        ),
      );
    }

    final hasExamples = easeZones.exampleRefs.isNotEmpty;
    
    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        // Header
        AnimatedOpacity(
          duration: const Duration(milliseconds: 400),
          opacity: _revealedSections.contains(0) ? 1.0 : 0.3,
          child: Card(
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            child: Padding(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          gradient: LinearGradient(
                            colors: [Colors.green.shade400, Colors.green.shade600],
                          ),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: const Icon(Icons.favorite_border, color: Colors.white, size: 28),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Where It Works Naturally',
                              style: theme.textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w700),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              'Areas of natural flow and connection',
                              style: theme.textTheme.bodySmall?.copyWith(
                                color: theme.colorScheme.onSurfaceVariant,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  if (easeZones.summary != null) ...[
                    const SizedBox(height: 20),
                    Text(
                      easeZones.summary!,
                      style: theme.textTheme.bodyLarge?.copyWith(
                        height: 1.6,
                        fontStyle: FontStyle.italic,
                      ),
                    ),
                  ],
                ],
              ),
            ),
          ),
        ),
        const SizedBox(height: 16),
        // Zones list (with detail if available)
        ...(easeZones.zonesWithExamples.isNotEmpty 
            ? easeZones.zonesWithExamples.asMap().entries.map((entry) {
                final index = entry.key;
                final zoneDetail = entry.value;
                final isRevealed = _revealedSections.contains(index + 1);
                
                return AnimatedOpacity(
                  duration: const Duration(milliseconds: 400),
                  opacity: isRevealed ? 1.0 : 0.3,
                  child: AnimatedContainer(
                    duration: const Duration(milliseconds: 400),
                    transform: Matrix4.translationValues(isRevealed ? 0 : 20, 0, 0),
                    child: Card(
                      margin: const EdgeInsets.only(bottom: 12),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      child: Padding(
                        padding: const EdgeInsets.all(16),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Container(
                                  width: 36,
                                  height: 36,
                                  decoration: BoxDecoration(
                                    color: Colors.green.shade100,
                                    shape: BoxShape.circle,
                                  ),
                                  child: Icon(Icons.check, color: Colors.green.shade700, size: 20),
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: Text(
                                    zoneDetail.zone ?? '',
                                    style: theme.textTheme.titleMedium?.copyWith(
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            if (zoneDetail.description != null) ...[
                              const SizedBox(height: 8),
                              Text(
                                zoneDetail.description!,
                                style: theme.textTheme.bodyMedium?.copyWith(height: 1.5),
                              ),
                            ],
                            if (zoneDetail.example != null) ...[
                              const SizedBox(height: 12),
                              Container(
                                padding: const EdgeInsets.all(10),
                                decoration: BoxDecoration(
                                  color: Colors.green.shade50,
                                  borderRadius: BorderRadius.circular(8),
                                  border: Border.all(color: Colors.green.shade200),
                                ),
                                child: Row(
                                  children: [
                                    Icon(Icons.movie_outlined, size: 16, color: Colors.green.shade700),
                                    const SizedBox(width: 8),
                                    Expanded(
                                      child: Text(
                                        '${zoneDetail.example!.characterName ?? 'Character'} in "${zoneDetail.example!.reference?.title ?? 'Story'}"',
                                        style: theme.textTheme.bodySmall?.copyWith(
                                          color: Colors.green.shade800,
                                          fontWeight: FontWeight.w500,
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ],
                        ),
                      ),
                    ),
                  ),
                );
              })
            : easeZones.zones.asMap().entries.map((entry) {
                final index = entry.key;
                final zone = entry.value;
                final isRevealed = _revealedSections.contains(index + 1);
                
                return AnimatedOpacity(
                  duration: const Duration(milliseconds: 400),
                  opacity: isRevealed ? 1.0 : 0.3,
                  child: AnimatedContainer(
                    duration: const Duration(milliseconds: 400),
                    transform: Matrix4.translationValues(isRevealed ? 0 : 20, 0, 0),
                    child: Card(
                      margin: const EdgeInsets.only(bottom: 12),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      child: Padding(
                        padding: const EdgeInsets.all(16),
                        child: Row(
                          children: [
                            Container(
                              width: 36,
                              height: 36,
                              decoration: BoxDecoration(
                                color: Colors.green.shade100,
                                shape: BoxShape.circle,
                              ),
                              child: Icon(Icons.check, color: Colors.green.shade700, size: 20),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: Text(
                                zone,
                                style: theme.textTheme.bodyMedium?.copyWith(height: 1.5),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                );
              })),
        // Examples button
        if (hasExamples) ...[
          const SizedBox(height: 8),
          Card(
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            child: InkWell(
              onTap: () {
                final converted = easeZones.exampleRefs.map(_convertToExampleItem).toList();
                showExamplesSheet(
                  context: context,
                  examples: converted,
                  sectionTitle: 'Ease Zones',
                );
              },
              borderRadius: BorderRadius.circular(12),
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(10),
                      decoration: BoxDecoration(
                        color: Colors.green.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(10),
                      ),
                      child: Icon(Icons.movie_outlined, color: Colors.green.shade600, size: 24),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('View Examples', style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600)),
                          Text(
                            '${easeZones.exampleRefs.length} example${easeZones.exampleRefs.length > 1 ? 's' : ''} from their stories',
                            style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant),
                          ),
                        ],
                      ),
                    ),
                    Icon(Icons.chevron_right, color: theme.colorScheme.onSurfaceVariant),
                  ],
                ),
              ),
            ),
          ),
        ],
      ],
    );
  }
}

// ============================================================================
// NEW: Rupture Loops Tab - Where the relationship breaks
// ============================================================================
class _RuptureLoopsTab extends StatefulWidget {
  final RelationshipOutput output;
  final Color accentColor;

  const _RuptureLoopsTab({required this.output, required this.accentColor});

  @override
  State<_RuptureLoopsTab> createState() => _RuptureLoopsTabState();
}

class _RuptureLoopsTabState extends State<_RuptureLoopsTab> {
  final Set<int> _revealedSections = {};

  @override
  void initState() {
    super.initState();
    _startProgressiveReveal();
  }

  void _startProgressiveReveal() {
    final loops = widget.output.ruptureLoops?.loops ?? [];
    for (int i = 0; i <= loops.length; i++) {
      Future.delayed(Duration(milliseconds: 150 * i), () {
        if (mounted) setState(() => _revealedSections.add(i));
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final ruptureLoops = widget.output.ruptureLoops;

    if (ruptureLoops == null || ruptureLoops.loops.isEmpty) {
      return Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.warning_amber, size: 48, color: Colors.orange.withOpacity(0.5)),
            const SizedBox(height: 16),
            Text('Rupture loops data not available', style: theme.textTheme.bodyLarge),
            const SizedBox(height: 8),
            Text(
              'Try regenerating the relationship analysis',
              style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant),
            ),
          ],
        ),
      );
    }

    final hasExamples = ruptureLoops.exampleRefs.isNotEmpty;
    
    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        // Header
        AnimatedOpacity(
          duration: const Duration(milliseconds: 400),
          opacity: _revealedSections.contains(0) ? 1.0 : 0.3,
          child: Card(
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            child: Padding(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          gradient: LinearGradient(
                            colors: [Colors.orange.shade400, Colors.orange.shade600],
                          ),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: const Icon(Icons.warning_amber, color: Colors.white, size: 28),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Where It Breaks',
                              style: theme.textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w700),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              'Recurring conflict patterns and triggers',
                              style: theme.textTheme.bodySmall?.copyWith(
                                color: theme.colorScheme.onSurfaceVariant,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  if (ruptureLoops.summary != null) ...[
                    const SizedBox(height: 20),
                    Text(
                      ruptureLoops.summary!,
                      style: theme.textTheme.bodyLarge?.copyWith(
                        height: 1.6,
                        fontStyle: FontStyle.italic,
                      ),
                    ),
                  ],
                ],
              ),
            ),
          ),
        ),
        const SizedBox(height: 16),
        // Loops list
        ...ruptureLoops.loops.asMap().entries.map((entry) {
          final index = entry.key;
          final loop = entry.value;
          final isRevealed = _revealedSections.contains(index + 1);
          
          return AnimatedOpacity(
            duration: const Duration(milliseconds: 400),
            opacity: isRevealed ? 1.0 : 0.3,
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 400),
              transform: Matrix4.translationValues(isRevealed ? 0 : 20, 0, 0),
              child: Card(
                margin: const EdgeInsets.only(bottom: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                child: Padding(
                  padding: const EdgeInsets.all(20),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Loop name
                      Row(
                        children: [
                          Container(
                            width: 40,
                            height: 40,
                            decoration: BoxDecoration(
                              gradient: LinearGradient(
                                colors: [Colors.orange.shade400, Colors.red.shade400],
                              ),
                              borderRadius: BorderRadius.circular(10),
                            ),
                            child: Center(
                              child: Text(
                                '${index + 1}',
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontWeight: FontWeight.bold,
                                  fontSize: 18,
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Text(
                              loop.name ?? 'Pattern ${index + 1}',
                              style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 16),
                      // Trigger
                      if (loop.trigger != null) ...[
                        _buildLoopSection(context, 'Trigger', loop.trigger!, Icons.bolt, Colors.amber),
                        const SizedBox(height: 12),
                      ],
                      // Pattern
                      if (loop.pattern != null) ...[
                        _buildLoopSection(context, 'Pattern', loop.pattern!, Icons.loop, Colors.orange),
                        const SizedBox(height: 12),
                      ],
                      // Repair
                      if (loop.repair != null) ...[
                        _buildLoopSection(context, 'Repair Path', loop.repair!, Icons.healing, Colors.green),
                      ],
                    ],
                  ),
                ),
              ),
            ),
          );
        }),
        // Examples button
        if (hasExamples) ...[
          const SizedBox(height: 8),
          Card(
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            child: InkWell(
              onTap: () {
                final converted = ruptureLoops.exampleRefs.map(_convertToExampleItem).toList();
                showExamplesSheet(
                  context: context,
                  examples: converted,
                  sectionTitle: 'Rupture Loops',
                );
              },
              borderRadius: BorderRadius.circular(12),
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Row(
                  children: [
                    Container(
                      padding: const EdgeInsets.all(10),
                      decoration: BoxDecoration(
                        color: Colors.orange.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(10),
                      ),
                      child: Icon(Icons.movie_outlined, color: Colors.orange.shade600, size: 24),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('View Examples', style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600)),
                          Text(
                            '${ruptureLoops.exampleRefs.length} example${ruptureLoops.exampleRefs.length > 1 ? 's' : ''} from their stories',
                            style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant),
                          ),
                        ],
                      ),
                    ),
                    Icon(Icons.chevron_right, color: theme.colorScheme.onSurfaceVariant),
                  ],
                ),
              ),
            ),
          ),
        ],
      ],
    );
  }

  Widget _buildLoopSection(BuildContext context, String label, String content, IconData icon, Color color) {
    final theme = Theme.of(context);
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, color: color, size: 20),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  label,
                  style: theme.textTheme.labelMedium?.copyWith(
                    color: color,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  content,
                  style: theme.textTheme.bodyMedium?.copyWith(height: 1.5),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ============================================================================
// NEW: What-If Scenarios Tab
// ============================================================================
class _WhatIfScenariosTab extends StatefulWidget {
  final RelationshipOutput output;
  final Color accentColor;

  const _WhatIfScenariosTab({required this.output, required this.accentColor});

  @override
  State<_WhatIfScenariosTab> createState() => _WhatIfScenariosTabState();
}

class _WhatIfScenariosTabState extends State<_WhatIfScenariosTab> {
  final Set<int> _revealedSections = {};
  int? _expandedScenario;

  @override
  void initState() {
    super.initState();
    _startProgressiveReveal();
  }

  void _startProgressiveReveal() {
    final scenarios = widget.output.whatIfScenarios;
    for (int i = 0; i <= scenarios.length; i++) {
      Future.delayed(Duration(milliseconds: 150 * i), () {
        if (mounted) setState(() => _revealedSections.add(i));
      });
    }
  }

  IconData _getThemeIcon(String theme) {
    switch (theme.toLowerCase()) {
      case 'conflict':
        return Icons.flash_on;
      case 'intimacy':
        return Icons.favorite;
      case 'trust':
        return Icons.security;
      case 'autonomy':
        return Icons.flight_takeoff;
      case 'authority':
        return Icons.gavel;
      case 'jealousy':
        return Icons.warning;
      case 'loyalty':
        return Icons.handshake;
      case 'boundaries':
        return Icons.border_all;
      case 'power_imbalance':
        return Icons.balance;
      case 'priorities':
        return Icons.priority_high;
      default:
        return Icons.psychology;
    }
  }

  Color _getThemeColor(String theme) {
    switch (theme.toLowerCase()) {
      case 'conflict':
        return Colors.red;
      case 'intimacy':
        return Colors.pink;
      case 'trust':
        return Colors.blue;
      case 'autonomy':
        return Colors.teal;
      case 'authority':
        return Colors.deepPurple;
      case 'jealousy':
        return Colors.orange;
      case 'loyalty':
        return Colors.indigo;
      case 'boundaries':
        return Colors.amber;
      case 'power_imbalance':
        return Colors.brown;
      case 'priorities':
        return Colors.cyan;
      default:
        return Colors.purple;
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scenarios = widget.output.whatIfScenarios;

    if (scenarios.isEmpty) {
      return Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.psychology, size: 48, color: widget.accentColor.withOpacity(0.5)),
            const SizedBox(height: 16),
            Text('What-If scenarios not available', style: theme.textTheme.bodyLarge),
            const SizedBox(height: 8),
            Text(
              'Try regenerating the relationship analysis',
              style: theme.textTheme.bodySmall?.copyWith(color: theme.colorScheme.onSurfaceVariant),
            ),
          ],
        ),
      );
    }

    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        // Header
        AnimatedOpacity(
          duration: const Duration(milliseconds: 400),
          opacity: _revealedSections.contains(0) ? 1.0 : 0.3,
          child: Card(
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            child: Padding(
              padding: const EdgeInsets.all(20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          gradient: LinearGradient(
                            colors: [widget.accentColor, widget.accentColor.withOpacity(0.7)],
                          ),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: const Icon(Icons.psychology, color: Colors.white, size: 28),
                      ),
                      const SizedBox(width: 16),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'What-If Scenarios',
                              style: theme.textTheme.titleLarge?.copyWith(fontWeight: FontWeight.w700),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              'Key relationship moments with conscious paths',
                              style: theme.textTheme.bodySmall?.copyWith(
                                color: theme.colorScheme.onSurfaceVariant,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
        const SizedBox(height: 16),
        // Scenarios
        ...scenarios.asMap().entries.map((entry) {
          final index = entry.key;
          final scenario = entry.value;
          final isRevealed = _revealedSections.contains(index + 1);
          final isExpanded = _expandedScenario == index;
          final themeColor = _getThemeColor(scenario.theme);
          
          return AnimatedOpacity(
            duration: const Duration(milliseconds: 400),
            opacity: isRevealed ? 1.0 : 0.3,
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 400),
              transform: Matrix4.translationValues(isRevealed ? 0 : 20, 0, 0),
              child: Card(
                margin: const EdgeInsets.only(bottom: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                clipBehavior: Clip.antiAlias,
                child: Column(
                  children: [
                    // Header - always visible
                    InkWell(
                      onTap: () {
                        setState(() {
                          _expandedScenario = isExpanded ? null : index;
                        });
                      },
                      child: Container(
                        padding: const EdgeInsets.all(20),
                        decoration: BoxDecoration(
                          gradient: LinearGradient(
                            colors: [
                              themeColor.withOpacity(0.1),
                              themeColor.withOpacity(0.05),
                            ],
                          ),
                        ),
                        child: Row(
                          children: [
                            Container(
                              width: 44,
                              height: 44,
                              decoration: BoxDecoration(
                                color: themeColor.withOpacity(0.2),
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(color: themeColor.withOpacity(0.3)),
                              ),
                              child: Icon(_getThemeIcon(scenario.theme), color: themeColor, size: 24),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    'When: ${_formatTheme(scenario.theme)}',
                                    style: theme.textTheme.titleMedium?.copyWith(
                                      fontWeight: FontWeight.w600,
                                      color: themeColor,
                                    ),
                                  ),
                                  if (scenario.setup != null) ...[
                                    const SizedBox(height: 4),
                                    Text(
                                      scenario.setup!,
                                      style: theme.textTheme.bodySmall?.copyWith(
                                        color: theme.colorScheme.onSurfaceVariant,
                                      ),
                                      maxLines: isExpanded ? null : 2,
                                      overflow: isExpanded ? null : TextOverflow.ellipsis,
                                    ),
                                  ],
                                ],
                              ),
                            ),
                            Icon(
                              isExpanded ? Icons.expand_less : Icons.expand_more,
                              color: themeColor,
                            ),
                          ],
                        ),
                      ),
                    ),
                    // Expanded content
                    if (isExpanded) ...[
                      Padding(
                        padding: const EdgeInsets.all(20),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            // Unconscious Pattern
                            if (scenario.unconsciousPattern != null)
                              _buildScenarioSection(
                                context,
                                'Unconscious Pattern',
                                scenario.unconsciousPattern!,
                                Icons.psychology_alt,
                                Colors.grey.shade600,
                              ),
                            // Two paths
                            const SizedBox(height: 16),
                            Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                // Unconscious path
                                Expanded(
                                  child: _buildPathCard(
                                    context,
                                    'Unconscious Path',
                                    scenario.unconsciousPath ?? '',
                                    Icons.cloud,
                                    Colors.grey,
                                    isNegative: true,
                                  ),
                                ),
                                const SizedBox(width: 12),
                                // Conscious path
                                Expanded(
                                  child: _buildPathCard(
                                    context,
                                    'Conscious Path',
                                    scenario.consciousPath ?? '',
                                    Icons.wb_sunny,
                                    Colors.amber.shade700,
                                    isNegative: false,
                                  ),
                                ),
                              ],
                            ),
                            // Actions
                            if (scenario.actions.isNotEmpty) ...[
                              const SizedBox(height: 16),
                              Text(
                                'Actions That Help',
                                style: theme.textTheme.labelLarge?.copyWith(
                                  color: Colors.green.shade700,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                              const SizedBox(height: 8),
                              ...scenario.actions.map((action) => Padding(
                                padding: const EdgeInsets.only(bottom: 6),
                                child: Row(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Icon(Icons.check_circle, color: Colors.green, size: 18),
                                    const SizedBox(width: 8),
                                    Expanded(
                                      child: Text(action, style: theme.textTheme.bodyMedium),
                                    ),
                                  ],
                                ),
                              )),
                            ],
                            // Avoid
                            if (scenario.avoid.isNotEmpty) ...[
                              const SizedBox(height: 16),
                              Text(
                                'What to Avoid',
                                style: theme.textTheme.labelLarge?.copyWith(
                                  color: Colors.red.shade700,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                              const SizedBox(height: 8),
                              ...scenario.avoid.map((item) => Padding(
                                padding: const EdgeInsets.only(bottom: 6),
                                child: Row(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Icon(Icons.cancel, color: Colors.red, size: 18),
                                    const SizedBox(width: 8),
                                    Expanded(
                                      child: Text(item, style: theme.textTheme.bodyMedium),
                                    ),
                                  ],
                                ),
                              )),
                            ],
                          ],
                        ),
                      ),
                    ],
                  ],
                ),
              ),
            ),
          );
        }),
      ],
    );
  }

  String _formatTheme(String theme) {
    return theme
        .replaceAll('_', ' ')
        .split(' ')
        .map((word) => word.isEmpty ? '' : '${word[0].toUpperCase()}${word.substring(1)}')
        .join(' ');
  }

  Widget _buildScenarioSection(
    BuildContext context,
    String label,
    String content,
    IconData icon,
    Color color,
  ) {
    final theme = Theme.of(context);
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(10),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, color: color, size: 20),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  label,
                  style: theme.textTheme.labelMedium?.copyWith(
                    color: color,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                const SizedBox(height: 4),
                Text(content, style: theme.textTheme.bodyMedium?.copyWith(height: 1.5)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPathCard(
    BuildContext context,
    String title,
    String content,
    IconData icon,
    Color color, {
    required bool isNegative,
  }) {
    final theme = Theme.of(context);
    
    // FIX: Both paths use light backgrounds, so text must always be dark
    // regardless of dark/light mode
    final textColor = isNegative ? Colors.grey.shade700 : Colors.amber.shade900;
    
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: isNegative ? Colors.grey.shade100 : Colors.amber.shade50,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(
          color: isNegative ? Colors.grey.shade300 : Colors.amber.shade200,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(icon, color: color, size: 18),
              const SizedBox(width: 6),
              Expanded(
                child: Text(
                  title,
                  style: theme.textTheme.labelMedium?.copyWith(
                    color: color,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: theme.textTheme.bodySmall?.copyWith(
              height: 1.5,
              color: textColor, // FIX: Use explicit dark color for readability
            ),
          ),
        ],
      ),
    );
  }
}
