import 'package:flutter/material.dart';
import '../models/generated_output.dart';

/// Sheet displaying examples for a specific section
/// Examples show real scenes from characters' films/series/books
class ExamplesSheet extends StatelessWidget {
  final List<ExampleItem> examples;
  final String sectionTitle;

  const ExamplesSheet({
    super.key,
    required this.examples,
    required this.sectionTitle,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    
    return DraggableScrollableSheet(
      initialChildSize: 0.7,
      minChildSize: 0.4,
      maxChildSize: 0.95,
      builder: (context, scrollController) {
        return Container(
          decoration: BoxDecoration(
            color: theme.scaffoldBackgroundColor,
            borderRadius: const BorderRadius.vertical(top: Radius.circular(20)),
          ),
          child: Column(
            children: [
              // Handle
              Container(
                margin: const EdgeInsets.only(top: 12),
                width: 40,
                height: 4,
                decoration: BoxDecoration(
                  color: Colors.grey[300],
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
              // Title
              Padding(
                padding: const EdgeInsets.all(16),
                child: Row(
                  children: [
                    Icon(
                      Icons.movie_outlined,
                      color: theme.primaryColor,
                    ),
                    const SizedBox(width: 8),
                    Text(
                      'Examples: $sectionTitle',
                      style: theme.textTheme.titleLarge?.copyWith(
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ],
                ),
              ),
              // Examples list
              Expanded(
                child: examples.isEmpty
                    ? _buildEmptyState(context)
                    : ListView.builder(
                        controller: scrollController,
                        padding: const EdgeInsets.symmetric(horizontal: 16),
                        itemCount: examples.length,
                        itemBuilder: (context, index) {
                          return ExampleCard(
                            example: examples[index],
                            index: index + 1,
                          );
                        },
                      ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildEmptyState(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            Icons.movie_filter_outlined,
            size: 64,
            color: Colors.grey[400],
          ),
          const SizedBox(height: 16),
          Text(
            'No examples available',
            style: Theme.of(context).textTheme.titleMedium?.copyWith(
              color: Colors.grey[600],
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Examples will appear here after generation',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
              color: Colors.grey[500],
            ),
          ),
        ],
      ),
    );
  }
}

/// Individual example card showing a scene from a character's life
class ExampleCard extends StatelessWidget {
  final ExampleItem example;
  final int index;

  const ExampleCard({
    super.key,
    required this.example,
    required this.index,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isAutoGenerated = example.tier == 'B' || example.autoGenerated;

    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      elevation: 2,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header: Character name and reference
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Character avatar
                CircleAvatar(
                  backgroundColor: theme.primaryColor.withOpacity(0.1),
                  child: Text(
                    example.characterName.isNotEmpty
                        ? example.characterName[0].toUpperCase()
                        : '?',
                    style: TextStyle(
                      color: theme.primaryColor,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                // Character name and reference
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        example.characterName,
                        style: theme.textTheme.titleMedium?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 4),
                      _buildReferenceChip(context),
                    ],
                  ),
                ),
                // Auto-generated badge
                if (isAutoGenerated)
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 8,
                      vertical: 4,
                    ),
                    decoration: BoxDecoration(
                      color: Colors.orange.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(4),
                    ),
                    child: Text(
                      'Auto-generated',
                      style: theme.textTheme.labelSmall?.copyWith(
                        color: Colors.orange[700],
                        fontSize: 10,
                      ),
                    ),
                  ),
              ],
            ),
            const SizedBox(height: 16),
            
            // Situation
            _buildSection(
              context,
              icon: Icons.description_outlined,
              title: 'Situation',
              content: example.situation,
            ),
            const SizedBox(height: 12),

            // Actions taken
            _buildBulletSection(
              context,
              icon: Icons.flash_on_outlined,
              title: 'What they did',
              items: example.actions,
              color: Colors.blue,
            ),
            const SizedBox(height: 12),

            // Outcome and cost
            _buildBulletSection(
              context,
              icon: Icons.balance_outlined,
              title: 'Outcome & Cost',
              items: example.outcomeAndCost,
              color: Colors.deepPurple,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildReferenceChip(BuildContext context) {
    final ref = example.reference;
    final mediumIcon = _getMediumIcon(ref.medium);
    
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: Colors.grey[100],
        borderRadius: BorderRadius.circular(4),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            mediumIcon,
            size: 14,
            color: Colors.grey[700],
          ),
          const SizedBox(width: 4),
          Flexible(
            child: Text(
              '${ref.title} (${ref.year})',
              style: TextStyle(
                fontSize: 12,
                color: Colors.grey[700],
              ),
              overflow: TextOverflow.ellipsis,
            ),
          ),
        ],
      ),
    );
  }

  IconData _getMediumIcon(String medium) {
    switch (medium.toLowerCase()) {
      case 'film':
        return Icons.movie_outlined;
      case 'series':
        return Icons.tv_outlined;
      case 'book':
        return Icons.book_outlined;
      case 'real-event':
        return Icons.history_outlined;
      default:
        return Icons.article_outlined;
    }
  }

  Widget _buildSection(
    BuildContext context, {
    required IconData icon,
    required String title,
    required String content,
  }) {
    final theme = Theme.of(context);
    
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(icon, size: 16, color: Colors.grey[600]),
            const SizedBox(width: 4),
            Text(
              title,
              style: theme.textTheme.labelMedium?.copyWith(
                color: Colors.grey[600],
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
        const SizedBox(height: 6),
        Text(
          content,
          style: theme.textTheme.bodyMedium,
        ),
      ],
    );
  }

  Widget _buildBulletSection(
    BuildContext context, {
    required IconData icon,
    required String title,
    required List<String> items,
    required Color color,
  }) {
    final theme = Theme.of(context);
    
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(icon, size: 16, color: color.withOpacity(0.7)),
            const SizedBox(width: 4),
            Text(
              title,
              style: theme.textTheme.labelMedium?.copyWith(
                color: color.withOpacity(0.8),
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
        const SizedBox(height: 6),
        ...items.map((item) => Padding(
          padding: const EdgeInsets.only(left: 8, bottom: 4),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                margin: const EdgeInsets.only(top: 8),
                width: 4,
                height: 4,
                decoration: BoxDecoration(
                  color: color.withOpacity(0.5),
                  shape: BoxShape.circle,
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: Text(
                  item,
                  style: theme.textTheme.bodyMedium,
                ),
              ),
            ],
          ),
        )),
      ],
    );
  }
}

/// Helper function to show examples sheet
void showExamplesSheet({
  required BuildContext context,
  required List<ExampleItem> examples,
  required String sectionTitle,
}) {
  showModalBottomSheet(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.transparent,
    builder: (context) => ExamplesSheet(
      examples: examples,
      sectionTitle: sectionTitle,
    ),
  );
}
